// pub const MINECRAFT_DATA_SUBMODULE_PATH: &str = "./minecraft-data";

// Instead, include the file generated by build.rs
// This makes the path available as `constants::VENDORED_MINECRAFT_DATA_PATH`
include!(concat!(env!("OUT_DIR"), "/vendored_data_path.rs"));